# Set terminal to use 256 colors
set -g default-terminal "screen-256color"

# Set base index of windows to 1
set -g base-index 1

# Reduce delay after pressing <esc>
set -sg escape-time 10

# Set window title
set-window-option -g automatic-rename on
set-option -g set-titles on

# Mouse
set -g mouse on

## Toggle mouse
bind m \
	set -g mouse on \;\
	display 'Mouse: ON'

## Toggle mouse off
bind M \
	set -g mouse off \;\
	display 'Mouse: OFF'

# Key bindings
# bind H split-window -h
# bind V split-window -v

bind h select-pane -L
bind j select-pane -D
bind k select-pane -U
bind l select-pane -R

## Resize panes using prefix + option + arrow
bind-key -r -T prefix       M-Up              resize-pane -U
bind-key -r -T prefix       M-Down            resize-pane -D
bind-key -r -T prefix       M-Left            resize-pane -L
bind-key -r -T prefix       M-Right           resize-pane -R

# Status bar
set -g status-interval 5    # set update frequency
set -g status-bg 'colour9'
## Left
set -g status-left-length 85
set -g status-left '#(~/.dotfiles/tmux/scripts/status_bar_left.sh)'
## Right
set -g status-right-length 85
set -g status-right '#(~/.dotfiles/tmux/scripts/status_bar_right.sh)'
