cask_args appdir: '/Applications/'

tap 'homebrew/bundle'
tap FelixKratz/formulae

brew 'neovim'
brew 'ripgrep'
brew 'fd'
brew 'pyenv'
brew 'pyenv-virtualenv'
brew 'xz'
brew 'pipx'
brew 'jq'
brew 'tmux'
brew 'starship'
brew 'borders'

cask 'kitty'
cask 'nikitabobko/tap/aerospace'
